name: otogapo_core
description: Otogapo Core Package
version: 0.1.0+1
publish_to: none

environment:
  sdk: "^3.3.0"
  flutter: "^3.19.0"

dependencies:
  extended_image: ^8.2.1
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  google_fonts: ^6.2.0
  mobile_scanner: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0
